services: 
  learn_jenkins_develop:
    container_name: learn_jenkins_develop
    image: arthurhozanna/learn_jenkins_develop:14c547d1e130824b753c3fbc254aeb9e244ac5b9-13
    ports:
      - "8001:8001"
    env_file:
      - .env