name: learn_jenkins_prod
services:
  learn_jenkins_prod:
    container_name: learn_jenkins_prod
    image: arthurhozanna/learn_jenkins_prod:a6f6534caf1a71dd630e0681c479eb1a589ef81a-44
    ports:
      - "8003:8003"
    environment:
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME_PROD}
      - PORT=${PORT}