services: 
  learn_jenkins_develop:
    container_name: learn_jenkins_dev
    image: arthurhozanna/learn_jenkins_develop:8d909bffaa4a5dd8330b21f56a9e86e309a2e91a-36
    ports:
      - "8001:8001"
    env_file:
      - .env